### PR TITLE
Resilient installation

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by CohenCyril** [comment]
Here is a failure:
https://github.com/coq-community/coq-nix-toolbox/runs/4118108940?check_suite_focus=true

**Comment by domenkozar** [comment]
It seems that the installer sometimes return 400, that could be fixed with --retry-on-error, but the curl on Debian doesn't support that yet.

**Comment by domenkozar** [comment]
@CohenCyril I pushed a fix that might work, can you give that a try? Thanks!

**Comment by domenkozar** [comment]
@CohenCyril I'll make a release tomorrow unless I hear you're still getting errors with this PR

**Comment by CohenCyril** [comment]
> @CohenCyril I'll make a release tomorrow unless I hear you're still getting errors with this PR

No error so far...

**Comment by domenkozar** [comment]
Thanks a lot!

**Pull request merged**
