### PR TITLE
Add NIX_PATH action input

### PR DESCRIPTION
**Pull request by Gerschtli**
Hey, this adds a new input named `nixpkgs` as default nixpkgs channel.

Resolves https://github.com/cachix/install-nix-action/issues/17.
Resolves https://github.com/cachix/install-nix-action/issues/6.

### CODE REVIEW

**Comment by domenkozar** [comment]
Wouldn't be setting NIX_PATH #6 be somewhat the same? I quite dislike channels, ideally, we'd disable Nix installation to set up a channel altogether.

**Comment by Gerschtli** [comment]
You mean like `NIX_PATH=nixpkgs=channel:nixos-19.09`? In this Environment it wouldn't make any differences I think.

**Comment by Gerschtli** [comment]
I added NIX_PATH as action input and went with the backwards compatible way. Of course I can set NIX_PATH arg to required to be more strict, but this decision is up to you :)

**Comment by Gerschtli** [comment]
Rebased PR to recent changes in master

**Comment by Mic92** [comment]
I tried this branch using:

```
    - uses: Gerschtli/install-nix-action@4a3097b877f501d409dc2c7e95dd6c3809ba1e43
      with:
        NIX_PATH: nixpkgs=channel:nixos-unstable
```

but it fails finding `@actions/core`: https://github.com/Mic92/nur-packages/runs/658701232

What I am doing wrong?

**Comment by Gerschtli** [comment]
Try the branch `nix-path`, in this branch I have pushed the `node_modules` folder which is necessary. It will be created in the release process of this action.

**Comment by Mic92** [comment]
Thanks! Works perfectly now: https://github.com/Mic92/nur-packages/blob/master/.github/workflows/build.yml

**Comment by domenkozar** [comment]
I guess this would allow us to tell installer to skip setting up a channel :)

**Comment by Gerschtli** [comment]
Oh awesome, did know of this option!

**Comment by domenkozar** [comment]
I think I'd prefer the following behavior:

- by default it would do as currently, let installation set the channel
- `nixPath: false` would disable channel and enforce empty `NIX_PATH`
- `nixPath: ...` would set `NIX_PATH` and disable the channel

**Comment by domenkozar** [comment]
I've implemented `skip_adding_nixpkgs_channel` in #33 and what's missing is just adding docs for `NIX_PATH`

**Comment by Mic92** [comment]
Cool. I switched back to the official install-nix-action and just the NIX_PATH manually: https://github.com/Mic92/nur-packages/blob/46606aa4ceb2f7e1c6c1824e35bde4339760f666/.github/workflows/build.yml

**Comment by Gerschtli** [comment]
PTAL

**Comment by domenkozar** [comment]
Thanks for the patience @Gerschtli :)

**Pull request merged**
