### PR TITLE
add github_access_token option

### PR DESCRIPTION
**Pull request by zimbatm**
I'm starting to see rate limit issues with GitHub Actions more
frequently so I propose to make this option more readily available.

### CODE REVIEW

**Comment by zimbatm** [comment]
before I go and fix the issues, what do you think, is it worth the extra complexity?

**Comment by domenkozar** [comment]
Happy to merge this if CI passes :)

**Comment by zimbatm** [comment]
I think it's fixed but there is an issue with nix profiles

**Comment by NickHu** [comment]
Would love to see a new release for this action, so I can more readily use it, as I'm seeing the same issues! Thanks for your contribution!

**Comment by domenkozar** [comment]
Couldn't we just set it by default?

**Comment by zimbatm** [comment]
AFAIK `secrets.GITHUB_TOKEN` has to be passed explicitly. But this could become the default example in the README and nix.dev.

**Pull request merged**
